title: Strizhechenko's public blog
email: oleg.strizhechenko@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about linux, system development, ISP in Russia, networks,
  python. I'm interested in fast network packet processing, dpi,
  natural language processing, statistic, time series and machine
  learning. Also: linters, shell, influxdb and twitterbots.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: strizhechenko
twitter_username: strizhechenko

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
google_analytics: UA-101002168-1
