title: Strizhechenko's blog
email: oleg.strizhechenko@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about development, linux, networks & python.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://strizhechenko.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: strizhechenko

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
